CarApp/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from CarApp import views
from CarApp.views import predict_price
from .views import CustomLoginView
from .views import CustomLogoutView

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('home/', views.home, name='home'),
    path('landingpage/', views.home, name='landingpage'),
    path("", views.landingpage, name='landingpage'),
    path("home", views.home, name='home'),
    path("home2", views.home2, name='home2'),
    path("about", views.about, name='about'),
    path("about2", views.about2, name='about2'),
    path("Egarage", views.Egarage, name='Egarage'),
    path("contact", views.contact, name='contact'),
    path("CarBuy", views.Carbuy, name='CarBuy'),
    path("CarSell", views.CarSell, name='CarSell'),
    path("CPP", views.CPP, name='CPP'),
    path('car/<int:car_id>/', views.car_detail, name='car_detail'),
    path('predict_price/', predict_price, name='predict_price'),
]
    

    
    


CarSell/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "CarKoto Admin"
admin.site.index_title = "Welcome to CarKoto Portal"
admin.site.site_title = "Welcome to CarKoto"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('CarApp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CarApp/models.py
from django.db import models
from django.contrib.auth.models import User


class Ad(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    cname= models.CharField(max_length=50)
    phone= models.PositiveIntegerField()
    caddress= models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    registration = models.PositiveIntegerField()
    mileage = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    image1 = models.ImageField(upload_to='ad_images/')
    image2 = models.ImageField(upload_to='ad_images/')
    image3 = models.ImageField(upload_to='ad_images/')
    image4 = models.ImageField(upload_to='ad_images/')
    image5 = models.ImageField(upload_to='ad_images/')
    LOCATION_CHOICES = [
          ('Dhaka', 'Dhaka'),
        ('Chittagong', 'Chittagong'),
        ('Rajshahi', 'Rajshahi'),
        ('Sylhet', 'Sylhet'),
        ('Khulna', 'Khulna'),
        ('Barisal', 'Barisal'),
        ('Rangpur', 'Rangpur'),
        # Add more choices as needed
    ]

    location = models.CharField(max_length=20, choices=LOCATION_CHOICES)
    def __str__(self):
        return self.title



class UserCar(models.Model):
    car_name = models.CharField(max_length=50)
    car_model = models.CharField(max_length=50)
    client_name = models.CharField(max_length=100)
    client_mobile = models.CharField(max_length=20)
    client_address = models.TextField()
    car_problem = models.TextField()
    booking_date = models.DateField()

    def __str__(self):
        return f"{self.client_name}'s {self.car_name} {self.car_model}"



class Contact(models.Model):
    name = models.CharField(max_length=122)
    email =models.CharField(max_length=122)
    phone =models.CharField(max_length=12)
    desc = models.TextField()
    date = models.DateField()

    def __str__(self):
            return self.name

templates/CPP.html
{% extends 'base.html' %}

{% block title %}CarKoto | Predict Your Car Price{% endblock title %}
{% block body %}


<style>
    /* Add CSS styles here */
    body {
        background-color: #333; /* Dark grey background color */
    }

    .container {
        background-color: #fff; /* White container background color */
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Add a subtle box shadow */
    }

    .form-group {
        margin-bottom: 20px;
    }

    .btn-primary {
        background-color: #007bff; /* Blue button color */
        border: none;
    }

    .btn-primary:hover {
        background-color: #0056b3; /* Darker blue on hover */
    }

    /* Adjust the alert style */
    .alert-success {
        background-color: #5cb85c; /* Green background color */
        color: #fff; /* White text color */
        padding: 10px;
        border-radius: 5px;
    }
</style>



<div class="container mt-5">
    <h1 class="mb-4 text-center">Predict You Car Price Here</h1>

         <!-- Predicted Price Output -->
         {% if predicted_price %}
         <div class="mt-3 alert alert-success">
             <strong>Predicted Price:</strong> {{ predicted_price }} <b>TK<b>
         </div>
         {% endif %}

        <form method="post" action="{% url 'predict_price' %}" class="border p-4 rounded">
        {% csrf_token %}
        
        <!-- Transmission -->
        <div class="form-group">
            <label for="id_transmission">Transmission:</label>
            <select class="form-control opacity-75" id="id_transmission" name="transmission" required>
                <option value="Automatic">Automatic</option>
                <option value="Manual">Manual</option>
                <!-- Add more transmission options as needed -->
            </select>
        </div>

        <!-- Fuel Type -->
        <div class="form-group">
            <label for="id_fuel_type">Fuel Type:</label>
            <select class="form-control opacity-75" id="id_fuel_type" name="fuel_type" required>
                <option value="HYBRID">HYBRID</option>
                <option value="CNG and OIL">CNG and OIL</option>
                <option value="LPG and OIL">LPG and OIL</option>
                <option value="OIL">OIL</option>
                <!-- Add more fuel type options as needed -->
            </select>
        </div>

        <!-- Brand -->
        <div class="form-group">
            <label for="id_brand">Brand:</label>
            <select class="form-control opacity-75" id="id_brand" name="brand" required>
                <option value="Chevrolet">Chevrolet</option>
                <option value="Ford">Ford</option>
                <option value="Honda">Honda</option>
                <option value="Hyundai">Hyundai</option>
                <option value="Kia">Kia</option>
                <option value="Mahindra">Mahindra</option>
                <option value="Maruti Suzuki">Maruti Suzuki</option>
                <option value="Mazda">Mazda</option>
                <option value="Mitsubishi">Mitsubishi</option>
                <option value="Nissan">Nissan</option>
                <option value="Proton">Proton</option>
                <option value="SsangYong">SsangYong</option>
                <option value="Suzuki">Suzuki</option>
                <option value="Tata">Tata</option>
                <option value="Toyota">Toyota</option>
                <option value="BMW">BMW</option>
                <!-- Add more brand options as needed -->
            </select>
        </div>

        <!-- Car Model -->
        <div class="form-group">
            <label for="id_car_model">Car Model:</label>
            <select class="form-control opacity-75" id="id_car_model" name="car_model" required>
                <option value="320i">320i</option>
                <option value="5 Series">5 Series</option>
                <option value="APV">APV</option>
                <option value="Accent">Accent</option>
                <option value="Allion">Allion</option>
                <option value="Alphard">Alphard</option>
                <option value="Alto">Alto</option>
                <option value="Alto 800">Alto 800</option>
                <option value="Aqua">Aqua</option>
                <option value="Attrage">Attrage</option>
                <option value="Auris">Auris</option>
                <option value="Avanza">Avanza</option>
                <option value="Axela">Axela</option>
                <option value="Axio">Axio</option>
                <option value="Bluebird">Bluebird</option>
                <option value="C-Class">C-Class</option>
                <option value="C-HR">C-HR</option>
                <option value="CR-V">CR-V</option>
                <option value="CR-Z">CR-Z</option>
                <option value="CX-7">CX-7</option>
                <option value="Cami">Cami</option>
                <option value="Camry">Camry</option>
                <option value="Carina">Carina</option>
                <option value="Carryboy">Carryboy</option>
                <option value="Cefiro">Cefiro</option>
                <option value="City">City</option>
                <option value="CityRover">CityRover</option>
                <option value="Civic">Civic</option>
                <option value="Coaster">Coaster</option>
                <option value="Corolla">Corolla</option>
                <option value="Corona">Corona</option>
                <option value="Corsa">Corsa</option>
                <option value="Crown">Crown</option>
                <option value="Discovery">Discovery</option>
                <option value="Dualis">Dualis</option>
                <option value="Dyna">Dyna</option>
                <option value="E 250">E 250</option>
                <option value="Eco Sport">Eco Sport</option>
                <option value="Esquire">Esquire</option>
                <option value="Estima">Estima</option>
                <option value="Fielder">Fielder</option>
                <option value="Fiesta">Fiesta</option>
                <option value="Fit">Fit</option>
                <option value="GLA-Class">GLA-Class</option>
                <option value="GLX">GLX</option>
                <option value="Grace">Grace</option>
                <option value="H-RV">H-RV</option>
                <option value="H1">H1</option>
                <option value="H2">H2</option>
                <option value="HR-V">HR-V</option>
                <option value="Harrier">Harrier</option>
                <option value="Hiace">Hiace</option>
                <option value="Hilux">Hilux</option>
                <option value="Ikon">Ikon</option>
                <option value="Indigo Ecs">Indigo Ecs</option>
                <option value="Insight">Insight</option>
                <option value="Juke">Juke</option>
                <option value="Kluger">Kluger</option>
                <option value="Kyron">Kyron</option>
                <option value="Lancer">Lancer</option>
                <option value="Land Cruiser">Land Cruiser</option>
                <option value="LiteAce">LiteAce</option>
                <option value="MPV">MPV</option>
                <option value="MR2">MR2</option>
                <option value="Mark II">Mark II</option>
                <option value="Murano">Murano</option>
                <option value="NX">NX</option>
                <option value="Noah">Noah</option>
                <option value="Note">Note</option>
                <option value="Other Model">Other Model</option>
                <option value="Outlandar">Outlandar</option>
                <option value="Outlander">Outlander</option>
                <option value="Pajero">Pajero</option>
                <option value="Passo">Passo</option>
                <option value="Pathfinder">Pathfinder</option>
                <option value="Prado">Prado</option>
                <option value="Premio">Premio</option>
                <option value="Prius">Prius</option>
                <option value="Probox">Probox</option>
                <option value="Q5">Q5</option>
                <option value="RAV4">RAV4</option>
                <option value="RVR">RVR</option>
                <option value="RX">RX</option>
                <option value="RX-8">RX-8</option>
                <option value="Ractis">Ractis</option>
                <option value="Raum">Raum</option>
                <option value="RunX">RunX</option>
                <option value="Rush">Rush</option>
                <option value="S660">S660</option>
                <option value="Santa Fe">Santa Fe</option>
                <option value="Satria">Satria</option>
                <option value="Sienta">Sienta</option>
                <option value="Sonata">Sonata</option>
                <option value="Spacio">Spacio</option>
                <option value="Spark">Spark</option>
                <option value="Sportage">Sportage</option>
                <option value="Sprinter">Sprinter</option>
                <option value="Starlet">Starlet</option>
                <option value="Starlet Soleil">Starlet Soleil</option>
                <option value="Succeed">Succeed</option>
                <option value="Sunny">Sunny</option>
                <option value="Swift">Swift</option>
                <option value="Terrano">Terrano</option>
                <option value="Tiida">Tiida</option>
                <option value="TownAce">TownAce</option>
                <option value="Tucson">Tucson</option>
                <option value="Urvan">Urvan</option>
                <option value="V6">V6</option>
                <option value="Vezel">Vezel</option>
                <option value="Vista">Vista</option>
                <option value="Vitz">Vitz</option>
                <option value="WagonR">WagonR</option>
                <option value="Wish">Wish</option>
                <option value="X Assista">X Assista</option>
                <option value="X-Trail">X-Trail</option>
                <option value="XJ">XJ</option>
                <option value="Yaris">Yaris</option>
                <option value="ist">ist</option>
                <option value="l200">l200</option>
                <option value="l300">l300</option>
                <option value="Belta">Belta</option>
            </select>
        </div>

        <!-- Registration -->
        <div class="form-group">
            <label for="id_registration">Registration:</label>
            <input type="text" class="form-control opacity-75" id="id_registration" name="registration" required>
        </div>

        <!-- Model Year -->
        <div class="form-group">
            <label for="id_model_year">Model Year:</label>
            <input type="text" class="form-control opacity-75" id="id_model_year" name="model_year" required>
        </div>

        <!-- Body Type -->
        <div class="form-group">
            <label for="id_body_type">Body Type:</label>
            <select class="form-control opacity-75" id="id_body_type" name="body_type" required>
                <option value="Estate">Estate</option>
                <option value="Hatchback">Hatchback</option>
                <option value="MPV">MPV</option>
                <option value="SUV / 4x4">SUV / 4x4</option>
                <option value="Saloon">Saloon</option>
                <!-- Add more body type options as needed -->
            </select>
        </div>

        <!-- Engine Capacity -->
        <div class="form-group">
            <label for="id_engine_capacity">Engine Capacity:</label>
            <select class="form-control opacity-75" id="id_engine_capacity" name="engine_capacity" required>
                <option value="800">800 cc</option>
                <option value="1000">1000 cc</option>
                <option value="1300">1300 cc</option>
                <option value="1500">1500 cc</option>
                <option value="1600">1600 cc</option>
                <option value="1800">1800 cc</option>
                <option value="2000">2000 cc</option>
                <option value="2500">2500 cc</option>
                <option value="2700">2700 cc</option>
                <option value="3000">3000 cc</option>
                <option value="3500">3500 cc</option>
                <option value="4000">4000 cc</option>

            </select>
        </div>

        <!-- Kilometers Run -->
        <div class="form-group">
            <label for="id_kilometers_run">Kilometers Run:</label>
            <input type="number" class="form-control opacity-75" id="id_kilometers_run" name="kilometers_run" required>
        </div>

        <!-- Submit Button -->
        <button type="submit" value="Predict" class="btn btn-primary">Predict Price</button>

   

    </form>

    
  
    
</div>





{% endblock body %}

templates/CarBuy.html
{% extends 'base.html' %}

{% block title %}CarKoto|Buy A Car{% endblock title %}

{% block body %}



<form class="form-inline d-flex justify-content-center mt-3" method="get" action="{% url 'CarBuy' %}">
    <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Search by Location" name="location_search">
        <div class="input-group-append">
            <button class="btn btn-primary p-1" type="submit">Search</button>
        </div>
    </div>
</form>



        <div class="container mx-auto px-4 py-8">
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
                {% for ad in ads %}
                <div class="col">
                    <a href="{% url 'car_detail' car_id=ad.id %}" style="text-decoration: none; color: inherit;">
                        <div class="card h-100 bg-dark">
                            <img src="{{ ad.image1.url }}" alt="{{ ad.title }} Image 1" class="card-img-top ad-image">
                            <div class="card-body text-white">
                                <h3 class="card-title"><b>{{ ad.title }}</b></h3>
                                <p class="card-text"><i><strong>Location:</strong></i> {{ ad.location }}</p><hr class="bg-light mb-2">
                                <p class="card-text"><i><strong>Mileage:</strong></i> {{ ad.mileage}}KM</p><hr class="bg-light mb-2">
                                <p class="card-text"><i><strong>Price:</strong></i> ৳{{ ad.price }}</p><hr class="bg-light mb-2">
                                <p class="card-text"><i><strong>Posted by:</strong> {{ ad.user.username }}</i></p>
                                
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="d-flex justify-content-center mt-4">
            <nav aria-label="Ads Pagination">
                <ul class="pagination custom-pagination">
                    {% if page.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a>
                    </li>
                    {% endif %}
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">{{ page.number }}</span>
                    </li>
                    {% if page.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>

   
<style>
    .card:hover  {
        transform: scale(1.1); /* Increase this value for stronger zoom effect */
        transition: transform 0.3s ease-in-out;
    }
    .ad-image {
        max-height: 200px; /* Adjust this value as needed */
        object-fit: cover;
        transition: transform 0.3s ease-in-out;
    }
    body {
        background-image: url('/static/temp images/carads3.jpg');
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
        
    }

  
    

</style>


{% endblock body %}

templates/CarSell.html
{% extends 'base.html' %}

{% block title %}CarKoto|Sell A Car{% endblock title %}


{% block body %}


    


      <div class="has-bg-img">
        <div class="bg-img bg-cover d-flex align-items-center justify-content-center" style="background-image: url('static/carousal images/img12.jpg');background-repeat:no-repeat; background-size:cover;">

        

           
            <div class="container mx-auto mt-10 opacity-75">
                <div class="containercarsell bg-dark rounded-lg">
                    <h1 class="text-center" style="color:white">Sell Your Car</h1>
                    <form method="post" enctype="multipart/form-data" action="{% url 'CarSell' %}">
                        {% csrf_token %}

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">    
                    <label for="cname" style="color:white">Client Name:</label>
                    <input type="text" id="cname" name="cname"><br>

                            </div>
                            <div class="col-md-6">      

                    <label for="phone" style="color:white">Phone:</label>
                    <input type="number" id="phone" name="phone"><br>
                            </div>
                            <div class="col-md-6">  

                    <label for="caddress" style="color:white">Address:</label>
                    <input type="text" id="caddress" name="caddress"><br> 
                            </div>

                            <div class="col-md-6">
                    <label for="location" style="color:white">Location:</label>
                    <select id="location" name="location" class="form-control">
                        {% for value, label in LOCATION_CHOICES %}
                          <option value="{{ value }}">{{ label }}</option>
                        {% endfor %}
                        </select>
                            </div>        

                            <div class="col-md-6">  

                    <label for="title" style="color:white">Title:</label>
                    <input type="text" id="title" name="title"><br>
                            </div>

                            <div class="col-md-6">  
            
                    <label for="brand" style="color:white">Brand:</label>
                    <input type="text" id="brand" name="brand"><br>

                            </div>

                            <div class="col-md-6">  

            
                    <label for="model"style="color:white">Model:</label>
                    <input type="text" id="model" name="model"><br>

                            </div>

                            <div class="col-md-6">  

                    <label for="mileage" style="color:white">Mileage:</label>
                    <input type="number" id="mileage" name="mileage"><br>

                            </div>

                            <div class="col-md-6">  
            
                    <label for="registration" style="color:white">Registration:</label>
                    <input type="number" id="registration" name="registration"><br>

                            </div>
                            <div class="col-md-6">  
            
                    <label for="price" style="color:white">Price:</label>
                    <input type="number" id="price" name="price"><br>
                            </div>
                            
            
                    <label for="description" style="color:white">Description:</label><br>
                    <textarea id="description" name="description" rows="4" cols="50"></textarea><br>
                    
            
                    <label for="image1" style="color:white">Image 1:</label>
                    <input type="file" id="image1" name="image1" style="color: transparent;"><br>
            
                    <label for="image2" style="color:white">Image 2:</label>
                    <input type="file" id="image2" name="image2" style="color: transparent;"><br>
            
                    <label for="image3" style="color:white">Image 3:</label>
                    <input type="file" id="image3" name="image3" style="color: transparent;"><br>
            
                    <label for="image4" style="color:white">Image 4:</label>
                    <input type="file" id="image4" name="image4" style="color: transparent;"><br>
            
                    <label for="image5" style="color:white">Image 5:</label>
                    <input type="file" id="image5" name="image5" style="color: transparent;"><br><br><br>
            
                    <button type="submit" class="btn btn-primary color:white">Submit</button>
                </form>
            
        </div>
    </div>
</div>
</div>

    <style>
        /* Adjust these styles as needed */
        .form-control {
          background-color: #333;
          color: white;
          border-color: #555;
        }
      
        .form-control:focus {
          border-color: #888;
          box-shadow: none;
        }
        

        /* Style for the dropdown */
        select.form-control {
            background-color: #333;
            color: white;
            border-color: #555;
        }
    
        select.form-control:focus {
            border-color: #888;
            box-shadow: none;
        }
       
      </style>
                
{% endblock body %}

templates/Egarage.html
{% extends 'base.html' %}

{% block title %}CarKoto|E-Garage{% endblock title %}


{% block body %}
<div class="has-bg-img">
    <div class="bg-img bg-cover d-flex align-items-center justify-content-cente" style="background-image:url('static/carousal images/e1.jpeg'); background-repeat:no-repeat; background-size:cover;">


   <div class="Egarageformcontainer w-50 container d-flex justify-content-center align-items-center">
    <div class="container ">
        <h1 class="text-white text-center font-family-">Add Car to eGarage</h1>
        <form method="post" class="mx-3 my-2 w-5 text-center p-3 bg-dark text-light  opacity-75" action="{% url 'Egarage' %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="carMake">Car Name:</label>
            <input type="text" class="form-control" id="carName" name="car_name" required>
          </div>
          <div class="form-group">
            <label for="carModel">Car Model:</label>
            <input type="text" class="form-control" id="carModel" name="car_model" required>
          </div>
          <div class="form-group">
            <label for="clientName">Client Name:</label>
            <input type="text" class="form-control" id="clientName" name="client_name" required>
          </div>
          <div class="form-group">
            <label for="clientMobile">Client Mobile Number:</label>
            <input type="tel" class="form-control" id="clientMobile" name="client_mobile" required>
          </div>
          <div class="form-group">
            <label for="clientAddress">Client Address:</label>
            <textarea class="form-control" id="clientAddress" name="client_address" rows="3" required></textarea>
          </div>
          <div class="form-group">
            <label for="carProblem">Description of Car Problem:</label>
            <textarea class="form-control" id="carProblem" name="car_problem" rows="3" required></textarea>
          </div>
          <div class="form-group">
            <label for="bookingDate">Appointment Date:</label>
            <input type="date" class="form-control" id="bookingDate" name="booking_date" required>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
      
   </div>
    </div>

</div>
{% endblock body%}

templates/about2.html
{% extends 'base.html' %}

{% block title %}CarKoto|About{% endblock title %}


{% block body %}

  <div class="has-bg-img">
         <div class="bg-img bg-cover" style="background-image: url('static/temp images/about2.jpg'); height:100vh; width:100%; background-repeat:no-repeat; background-size:cover; background-attachment: fixed;">
       
        
        <h2 class="text-center text-white">About Us</h2> <hr><hr>

    <div class="containerabout text-center bg-dark mx-5 p-5 opacity-75">


      <h2 style="color:white"><i>CarKoto</i></h2>
      <p style="color:white"> <b>CarKoto</b> is an online website for Bangladeshi used car buy & sell. This website established in 2023 and is currently in the testing process.<br> This website is not only bounded to vehicle buy and sell but also you can predict the price of your car using Artificial Inteligence using Machine Learning.<br> This is a CSE499 Senior Project and this project was done under the supervision of our honorable Faculty Member: <b>Dr. Mohammad Abdul Qayum.<b><br> We were altegether three members for this project: <br><b> Abdullah Nafis Chowdhury</b><br><b>192108104<b>2<br> <b>Sayem Ahmed Sajil<b><br><b>1921449642<b><br><b> Sabrina Jahan Akhi<b><br><b>1821164026<b> </p>
      </div>  
      
      </div>

    </div>
  

{% endblock body %}

templates/contact.html
{% extends 'base.html' %}

{% block title %}CarKoto|Contact{% endblock title %}


{% block body %}



<div class="container-contact-2 opacity-75 px-5">
  <h1 class="text-center text-light mb-5">Contact Us</h1>
    <form method="post" action="/contact" class="mx-auto p-2 col-12 col-md-12 col-lg-14 px-5 bg-dark rounded">
      {% csrf_token %}
      
        <div class="mb-3">
          <label for="name" class="form-label text-white">Name</label>
          <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name">
          
        <div class="mb-3">
            <label for="phone" class="form-label text-white">Phone</label>
            <input type="phone" class="form-control" id="phone" name="phone" placeholder="Enter your phone number">
            
          </div>

          <div class="mb-3">
            <label for="email" class="form-label text-white">Email address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text text-white">We'll never share your email with anyone else.</div>
          </div>
        <div class="mb-3">
          <label for="desc" class="form-label text-white">For Any Queries </label>
          <textarea class="form-control" id="desc" rows="3" name="desc"></textarea>
        </div>
        
        <button type="submit" class="btn btn-primary center-button">Submit</button>

      </form>


<style>

  body {
    background-image: url('/static/temp images/carads2.jpg');
    background-size: cover;
    background-repeat: no-repeat;
    background-attachment: fixed;
}

</style>


{% endblock body %}